<!DOCTYPE library [
<!ELEMENT library (books,members,staffs,publisher)>
<!ELEMENT books (book1,book2)>
<!ELEMENT book1 (title,author,year,isbn,price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT book2 (title,author,year,isbn,price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT members (member1,member2)>
<!ELEMENT member1 (name,address,phone)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT member2 (name,address,phone)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT staffs(staff1,staff2)>
<!ELEMENT staff1 (name,address,phone)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT staff2 (name,address,phone)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT publisher (name,address,phone)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST book1 bookId CDATA#REQUIRED>
<!ATTLIST book2 bookId CDATA#REQUIRED>
<!ATTLIST member1 memberId CDATA#REQUIRED>
<!ATTLIST member2 memberId CDATA#REQUIRED>
<!ATTLIST staff1 staffId CDATA#REQUIRED>
<!ATTLIST staff2 staffId CDATA#REQUIRED>
<!ATTLIST publisher publisId CDATA #REQUIRED>
]>
<library>
<books>
<book1 bookId="1">
<title>Web Designing</title>
<author>RAM</author>
<year>2020</year>
<isbn>3472538593134</isbn>
<price>234</price>
</book1>
<book2 bookId="2">
<title>Artificial Intelligence</title>
<author>SAMUEL</author>
<year>2020</year>
<isbn>35732748532</isbn>
<price>585</price>
</book2>
</books>
<members>
<member1 memberId="100">
<name>SEENU</name>
<address>ANATAPUR</address>
<phone>23456789</phone>
</member1>
<member2 memberId="101">
<name>MAHESH</name>
<address>Dharmavaramu</address>
<phone>8456123970</phone>
</member2>
</members>
<staffs>
<staff1 staffId="201">
<name>GOPAL</name>
<address>THADIPATRI</address>
<phone>8472538490</phone>
</staff1>
<staff2 staffId="202">
<name>Narayana</name>
<address>Kurnool</address>
<phone>7892345012</phone>
</staff2>
</staffs>
<publisher publishId="301">
<name>Chand</name>
<address>Delhi</address>
<phone>95756354758</phone>
</publisher>
</library>
